services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=parksight
      - POSTGRES_PASSWORD=parksight
      - POSTGRES_DB=parksight_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - parksight-net

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://parksight:parksight@db:5432/parksight_db
      - GROQ_API_KEY=${GROQ_API_KEY:-}
    volumes:
      - parksight-telemetry:/app/telemetry
    networks:
      - parksight-net

  edge:
    build:
      context: .
      dockerfile: docker/Dockerfile.edge
    depends_on:
      - api
    environment:
      - API_URL=http://api:8000/system/process
      - CAMERA_SOURCE=${CAMERA_SOURCE:-MOCK}
    volumes:
       - parksight-models:/app/edge/models
    networks:
      - parksight-net

  ui:
    build:
      context: .
      dockerfile: docker/Dockerfile.ui
    ports:
      - "3000:80"
    depends_on:
      - api
    networks:
      - parksight-net

volumes:
  postgres_data:
  parksight-telemetry:
  parksight-models:

networks:
  parksight-net:
    driver: bridge
