FROM python:3.10-slim
WORKDIR /app
COPY cloud/api /app/cloud/api
COPY langgraph /app/langgraph
WORKDIR /app/cloud/api
RUN pip install -r requirements.txt
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
