# Build stage
FROM node:18-slim AS build
WORKDIR /app
COPY ui/package.json ui/package-lock.json ./
RUN npm install
COPY ui ./
RUN npm run build

# Production stage
FROM nginx:alpine
COPY docker/nginx-ui.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
